<!doctype html>
<html land="en">

	<head>
		<meta charset="utf-8">
		<title><?php echo $currentPage; ?></title>
		<link rel="stylesheet" href ="css/styles.css">
	</head>

	<body class = "container">

		<header>
			<h1 class="homeh1" style = "font-size: 1.2em; left: -65px; font-size: 42px;" > We are DMS</h1>
		</header>

		<section class="section">
			<h2>Topics of Similarity</h2>
			<p>The aforementioned students are all declared Digital Media Studies Majors, and all go about discussing their early lives, interests, and why it is that they are a DMS major.</p>
		</section>